site:
  name: "יוליה קורנסקי | צילומי זוגיות | צילומי נשיות | צילומי ילדים | צילומי הריון"
  site: 'https://yulia.photography'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: 2oxqWrAppd4777x9FGU3D49eLEKoo3s1tc8e_LzPpgE

# Default SEO metadata
metadata:
  title:
    default: "יוליה קורנסקי | צילומי זוגיות | צילומי נשיות | צילומי ילדים | צילומי הריון"
    template: '%s — יוליה קורנסקי'
  description: "צילומי משפחה, צילומי זוגיות, צילומי הריון, בוק אישי - בטבע קסום. חוויית צילום טבעית ומרגשת שתשאיר זיכרונות לכל החיים. צרו קשר לקביעת סשן צילום מותאם אישית"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: "יוליה קורנסקי | צילומי זוגיות | צילומי נשיות | צילומי ילדים | צילומי הריון"
    images:
      - url: 'https://yulia.photography/images/structured/yulia-photographer.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: he
  textDirection: rtl

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'articles' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
